In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 2.3 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
print(a[0])

1


In [5]:
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [6]:
print(b[0,3])

4


In [7]:
b[0,3]=10
print(b)

[[ 1  2  3 10  5]
 [ 6  7  8  9  0]]
